const units=['El Derecho Administrativo','La función pública del Estado','El Poder Ejecutivo y la función administrativa','La administración pública','Legislación administrativa','Ética pública','El patrimonio público en México','Información pública','Participación ciudadana','Responsabilidad patrimonial del Estado'];
const types=[['Presentación','presentation'],['Guía común','guide'],['Guía interactiva','interactive'],['Mapa mental','map'],['Glosario','glossary'],['Fuentes','sources'],['Evaluación','evaluation'],['Guion docente','script'],['Sentencias','judgment']];
const refs=[['Constitución Política de los Estados Unidos Mexicanos','Normativa constitucional para legalidad y organización administrativa.',1,'sources'],['Ley Federal de Procedimiento Administrativo','Reglas del acto y procedimiento administrativo federal.',1,'judgment'],['Derecho administrativo · UNAM','Consulta doctrinal sobre concepto, evolución y fuentes.',1,'guide'],['Los principios generales del derecho administrativo','Obra doctrinal para el estudio de los principios de la disciplina.',0,'reference']];
const outcomes=['Explicar qué estudia el Derecho Administrativo y distinguirlo de la administración privada.','Reconocer sus fuentes formales y justificar cuál resulta aplicable.','Relacionarlo con otras ramas jurídicas y disciplinas no jurídicas.','Aplicar principios para revisar competencia, fundamentación y motivación.'];
const icon=name=>`<svg class="icon" aria-hidden="true"><use href="icons.svg#${name}"/></svg>`;
let selectedMaterial='';const content=document.querySelector('#content'),dialog=document.querySelector('#review-dialog');
function saved(){return JSON.parse(localStorage.getItem('da1521-demo-reviews')||'{}')}function go(view){document.querySelectorAll('#main-nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===view));document.querySelector('#page-title').textContent={home:'Inicio',units:'Unidades',pending:'Pendientes',subjects:'Materias',materials:'Materiales',references:'Referencias',archive:'Archivo'}[view];if(view==='home')home();else if(view==='units')unitList();else if(view==='references')referenceView();else generic(view);document.querySelector('#sidebar').classList.remove('open')}
function home(){const n=Object.keys(saved()).length;content.innerHTML=`<div class="stats"><div class="stat">${icon('units')}<strong>10</strong><span>unidades</span></div><div class="stat">${icon('material')}<strong>90</strong><span>materiales registrados</span></div><div class="stat">${icon('check')}<strong>${n}</strong><span>evaluaciones demo</span></div><div class="stat">${icon('clock')}<strong>${90-n}</strong><span>pendientes demo</span></div></div><section class="hero"><div class="hero-icon">${icon('evaluation')}</div><p class="eyebrow">ESTADO DEL SEMESTRE</p><h2>El catálogo está cubierto; falta evaluación editorial.</h2><p>Cada unidad registra los nueve tipos previstos. Revisa contenidos, citas, claridad y utilidad didáctica antes de aprobar.</p></section>`}
function unitList(){content.innerHTML=`<section class="panel"><div class="section-head"><h2>${icon('units')} Programa por unidades</h2><span class="badge">${icon('check')} 9/9 tipos registrados</span></div><div class="unit-grid">${units.map((u,i)=>`<button class="unit-card" onclick="unitView(${i+1})"><span class="unit-icon">${icon('subject')}</span><span><b>UNIDAD ${i+1}</b><strong>${u}</strong><small>${icon('material')} 9 materiales · abrir revisión</small></span></button>`).join('')}</div></section>`}
function unitView(id){document.querySelector('#page-title').textContent=`Unidad ${id}`;content.innerHTML=`<section class="hero unit-hero"><button class="back" onclick="unitList()">← Unidades</button><div class="hero-icon">${icon('subject')}</div><p class="eyebrow" style="margin-top:18px">UNIDAD ${id}</p><h2>${units[id-1]}</h2><p>${id===1?'Punto de partida del curso: concepto, evolución, fuentes, relaciones y principios que limitan la actuación administrativa.':'Vista de muestra: el contenido académico detallado se integrará desde el programa oficial.'}</p></section>${id===1?`<section class="panel"><div class="intro"><div><p class="eyebrow">${icon('target')} OBJETIVO</p><p>Identificar concepto, esencia, características, fuentes, principios y ubicación del Derecho Administrativo.</p></div><div><p class="eyebrow">${icon('syllabus')} TEMARIO</p><p>1.1 Generalidades · 1.2 Fuentes · 1.3 Relaciones · 1.4 Principios</p></div></div><h2 class="title-icon">${icon('student')} ¿Qué debe llevarse el alumnado?</h2><ol class="outcomes">${outcomes.map((x,i)=>`<li><span>${icon(i===3?'check':'student')}</span>${x}</li>`).join('')}</ol></section>`:''}<section class="panel"><div class="section-head"><h2>${icon('material')} Materiales</h2><span>${icon('check')} 9 registrados</span></div><div class="material-grid">${types.map(t=>materialCard(id,t)).join('')}</div></section>`}
function materialCard(id,[type,pictogram]){const key=`${id}-${type}`,review=saved()[key];return `<article class="material"><div class="material-top"><span class="material-pictogram">${icon(pictogram)}</span><div><small>${type}</small><h3>${type} · Unidad ${String(id).padStart(2,'0')}</h3></div></div><span class="badge ${review?.decision==='aprobado'?'ok':review?'correction':''}">${icon(review?.decision==='aprobado'?'check':review?'edit':'clock')} ${review?review.decision.replace('_',' '):'Sin evaluar'}</span><button onclick="review('${key}','${type}')">${icon('evaluation')} ${review?'Reevaluar':'Evaluar'}</button></article>`}
function review(key,title){selectedMaterial=key;document.querySelector('#review-title').textContent=title;document.querySelector('#rubric').innerHTML=[['Alineación con la unidad','target'],['Claridad para el alumnado','student'],['Rigor jurídico y citas','judgment'],['Utilidad didáctica','interactive']].map(([x,p],i)=>`<fieldset><legend><span class="rubric-icon">${icon(p)}</span><span><b>${x}</b><small>Valora este aspecto del material.</small></span></legend><div class="scores">${[1,2,3,4].map(n=>`<label><input required type="radio" name="c${i}" value="${n}"><span>${n}</span></label>`).join('')}</div></fieldset>`).join('');dialog.showModal()}
function store(decision){const data=new FormData(document.querySelector('#review-form')),scores=[0,1,2,3].map(i=>Number(data.get(`c${i}`)));if(scores.includes(0)){document.querySelector('#review-form').reportValidity();return}const all=saved();all[selectedMaterial]={decision,total:scores.reduce((a,b)=>a+b,0),notes:document.querySelector('#notes').value};localStorage.setItem('da1521-demo-reviews',JSON.stringify(all));dialog.close();unitView(Number(selectedMaterial.split('-')[0]))}
function referenceView(){content.innerHTML=`<section class="panel"><div class="section-head"><h2>${icon('reference')} Referencias utilizadas</h2><span>${icon('sources')} ${refs.length} fuentes de muestra</span></div><div class="reference-grid">${refs.map(r=>`<article class="reference"><div class="cover"><span>${icon(r[3])}</span>${r[0]}</div><div><span class="reference-icon">${icon(r[3])}</span><h3>${r[0]}</h3><p>${r[1]}</p>${r[2]?`<span class="rag">${icon('interactive')} Disponible para RAG</span>`:''}</div></article>`).join('')}</div></section>`}
function generic(view){const data={pending:['Pendientes','clock'],subjects:['Materias','subject'],materials:['Materiales','material'],archive:['Archivo','archive']},[name,pictogram]=data[view];content.innerHTML=`<section class="hero"><div class="hero-icon">${icon(pictogram)}</div><p class="eyebrow">${name.toUpperCase()}</p><h2>${name}</h2><p>Esta sección está incluida en la navegación de la maqueta. Sus datos completos permanecen en la aplicación local.</p></section>`}
document.querySelectorAll('#main-nav button').forEach(b=>b.onclick=()=>go(b.dataset.view));document.querySelector('#menu-button').onclick=()=>document.querySelector('#sidebar').classList.toggle('open');document.querySelector('.close').onclick=()=>dialog.close();document.querySelector('#review-form').onsubmit=e=>{e.preventDefault();store('aprobado')};document.querySelector('#correction').onclick=()=>store('requiere_correccion');go('units');
